# Ingeniería de Características
Vamos a preparar los datos para el modelo, codificando variables categoricas y generando algunas extras de ser necesario.

In [34]:
import pandas as pd 

df = pd.read_csv('../data/titanic_clean.csv')
df.head(3)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S

# Codificación de Variables Categóricas

In [35]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})

df = pd.get_dummies(df, columns=['Embarked'], prefix='Emb')

df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Emb_C  Emb_Q  Emb_S
0         0       3    0  22.0      1      0   7.2500  False  False   True
1         1       1    1  38.0      1      0  71.2833   True  False  False
2         1       3    1  26.0      0      0   7.9250  False  False   True
3         1       1    1  35.0      1      0  53.1000  False  False   True
4         0       3    0  35.0      0      0   8.0500  False  False   True

In [36]:
df.to_csv('../data/titanic_feature.csv', index=False)
print('Datos guardado en data/titanic_feature.csv')

Datos guardado en data/titanic_feature.csv

In [37]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

df = pd.read_csv('../data/titanic_feature.csv')
print(df.columns)
print(df.head())

x = df.drop(columns=['Survived'])
y = df['Survived']

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Emb_C',
       'Emb_Q', 'Emb_S'],
      dtype='str')
   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Emb_C  Emb_Q  Emb_S
0         0       3    0  22.0      1      0   7.2500  False  False   True
1         1       1    1  38.0      1      0  71.2833   True  False  False
2         1       3    1  26.0      0      0   7.9250  False  False   True
3         1       1    1  35.0      1      0  53.1000  False  False   True
4         0       3    0  35.0      0      0   8.0500  False  False   True